/**
 * testing.js
 * Route Handler File
 * Generated by Pug-Router for ApiHero
 *
 * REST Route: [findOne] '/Users/van/Documents/workspace-new/apihero-module-pug-router/src/testing'
 */
module.exports = function(testingHander) {
  /*
   * place your customazations below
   */
};